### ISSUE TITLE
0.21-stable cherry picks

### ISSUE THREAD

**Issue by rt2zz** [wildlifela/react-native#2]
f8542f2b6bbbe528b603ffd3932e911c72ebc1d0 (in master)
884cb360d0fa1203433e481202de037af18c68cc (in master)
0b9566fc7855aa4108f95f5f93648ee31270a4b3 (comparable in master)
aa3f73f1474dfce905bcd85e2cf8040423f5a9d6 (squash with related ip commit)

**Comment by christopherdro** [comment]
Geolocation Accuracy and Cached Location Bug
076c585adc665dfcff01d37a0ba3e8edef4d6885

@rt2zz
